Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2023-11, with the labels that each got.

#48 Implement kubeconfig rotation
  api/v1/gardenercluster_types.go
  cmd/main.go
  config/rbac/role.yaml
  config/samples/infrastructuremanager_v1_gardenercluster.yaml
  internal/controller/gardener_cluster_controller.go
  internal/controller/gardener_cluster_controller_test.go
  internal/controller/suite_test.go
Labels: size/XL, lgtm

#63 Fix cache error
  api/v1/gardenercluster_types.go
  internal/controller/gardener_cluster_controller.go
Labels: lgtm, size/M

#60 Fix #22 reuse folder has incorrect name
  .reuse/dep5
Labels: size/XS, lgtm

#49 adds target for convenient (re)building and (re)deployments
  Makefile
  README.md
  config/manager/kustomization.yaml
Labels: area/control-plane, size/S, lgtm

#64 refactor kubeconfig status
  internal/controller/gardener_cluster_controller.go
Labels: size/XS, lgtm

#65 switches security scanners config from a concrete image to the latest…
  sec-scanners-config.yaml
Labels: area/control-plane, size/XS, area/security, lgtm

#66 adds information about IM configuration and usage
  README.md
  docs/README.md
Labels: area/control-plane, area/documentation, lgtm, size/M

#67 Change the logic of reconciliation on unrecoverable error
  internal/controller/gardener_cluster_controller.go
Labels: size/XS, lgtm

#68 Update GardenerCluster CRD printed columns
  api/v1/gardenercluster_types.go
  config/crd/bases/infrastructuremanager.kyma-project.io_gardenerclusters.yaml
Labels: size/S, lgtm

#70 Fix invalid condition status for errors in GardenerCluster
  api/v1/gardenercluster_types.go
  internal/controller/gardener_cluster_controller.go
Labels: lgtm, size/M

#71 add module benchmark
  hack/benchmark/README.md
  hack/benchmark/benchmark.sh
  hack/benchmark/secret.template.json
Labels: lgtm, size/M

#73 Fix delete secret
  hack/benchmark/benchmark.sh
  hack/benchmark/secret.template.json
  internal/controller/gardener_cluster_controller.go
Labels: size/S, lgtm, cla: yes

#74 Add predicates to filter out CR status changes
  Makefile
  internal/controller/gardener_cluster_controller.go
Labels: size/XS, lgtm, cla: yes

#77 Fix kubeconfig rotation
  internal/controller/gardener_cluster_controller.go
Labels: area/control-plane, size/XS, lgtm, cla: yes
