Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2023-12, with the labels that each got.

#80 Create dependabot.yml
  .github/dependabot.yml
Labels: area/ci, size/S, lgtm, cla: yes

#85 fixes link to the license file
  README.md
Labels: size/XS, lgtm, cla: yes

#88 adds a licence file to the root directory
  LICENCE
Labels: lgtm, size/L, cla: yes

#89 [WiP] Metrics PoC
  internal/controller/gardener_cluster_controller.go
  internal/controller/metrics/metrics.go
Labels: lgtm, size/M, cla: yes

#93 renames control-manager to intrastructure-manager
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_gardener_secret_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
Labels: lgtm, size/M, cla: yes

#94 renames infrastructure manager roles and rolebindings
  Makefile
  config/manager/manager.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
Labels: size/S, lgtm, cla: yes

#95 fixes rotation regression
  internal/controller/gardener_cluster_controller.go
Labels: area/control-plane, size/XS, lgtm, cla: yes

#96 managed-by secret label is set to lifecycle-manager
  internal/controller/gardener_cluster_controller.go
  internal/controller/gardener_cluster_controller_test.go
Labels: size/XS, lgtm, cla: yes

#99 Fix timezone miss-matching
  internal/controller/gardener_cluster_controller.go
Labels: lgtm, size/M, cla: yes

#100 describes minimal-rotation-time parameter
  docs/README.md
Labels: area/documentation, size/XS, lgtm, cla: yes

#102 configures golang/govulncheck-action
  .github/workflows/golangci-lint.yaml
  .github/workflows/run-vuln-check.yaml
  Dockerfile
Labels: area/ci, size/S, lgtm, cla: yes

#107 Add requeue tests
  go.mod
  go.sum
  internal/controller/find_last_sync_time.go
  internal/controller/find_last_sync_time_test.go
  internal/controller/gardener_cluster_controller.go
  internal/controller/next_requeue.go
  internal/controller/next_requeue_test.go
Labels: lgtm, size/L, cla: yes

#114 changes managed-by label from lifecycle-manager to infrastructure-manager
  internal/controller/gardener_cluster_controller.go
  internal/controller/gardener_cluster_controller_test.go
Labels: size/XS, lgtm, cla: yes

#115 adjust configuration for metrics
  config/manager/manager.yaml
  config/manager/metrics.yaml
  config/prometheus/monitor.yaml
Labels: lgtm, size/M, cla: yes
