Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2023-09, with the labels that each got.

#6 should make the cluster-inventory reuse compliant
  .reuse/dep5
  LICENSE
  LICENSES/Apache-2.0.txt
  README.md
Labels: lgtm, size/L

#16 Make test should print output for few test cases, they should run in less than 30 seconds
  .dockerignore
  .gitignore
  DOCKERFILE
  Makefile
  PROJECT
  api/v1/cluster_types.go
  api/v1/groupversion_info.go
  api/v1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/clusterinventory.kyma-project.io_clusterinventories.yaml
  config/crd/bases/clusterinventory.kyma-project.io_clusters.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_clusters.yaml
  config/crd/patches/webhook_in_clusters.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/cluster_editor_role.yaml
  config/rbac/cluster_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/clusterinventory_v1_cluster.yaml
  config/samples/kustomization.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  internal/controller/cluster_controller.go
  internal/controller/suite_test.go
  pkg/provisioning/dynamic_kubeconfigs_test.go
  pkg/reconciler/verify_reconciler_test.go
  reuse/dep5
Labels: size/XXL, area/control-plane, lgtm

#12 Initializes cluster-inventory using kubebuilder
  .dockerignore
  .gitignore
  DOCKERFILE
  Makefile
  PROJECT
  cmd/main.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  reuse/dep5
Labels: size/XXL, area/control-plane

#17 GitHub action test runner
  .github/workflows/run-tests.yaml
Labels: area/control-plane, area/ci, lgtm, size/M

#25 adjust CODEOWNERS file in cluster inventory
  CODEOWNERS
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, size/M

#21 Adds initial content of the project README
  README.md
Labels: area/control-plane, area/documentation, lgtm, size/M

#7 Configure linter github action job
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  api/v1/groupversion_info.go
  cmd/main.go
  internal/controller/cluster_controller.go
  internal/controller/suite_test.go
  pkg/provisioning/dynamic_kubeconfigs_test.go
  pkg/reconciler/verify_reconciler_test.go
Labels: area/ci, lgtm, size/L

#31 Update README.md
  README.md
Labels: size/S, lgtm

#24 CRD structure prepared
  PROJECT
  api/v1/cluster_types.go
  api/v1/gardenercluster_types.go
  api/v1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/clusterinventory.kyma-project.io_clusterinventories.yaml
  config/crd/bases/clusterinventory.kyma-project.io_clusters.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_clusters.yaml
  config/crd/patches/webhook_in_clusters.yaml
  config/rbac/cluster_editor_role.yaml
  config/rbac/cluster_viewer_role.yaml
  config/samples/clusterinventory_v1_cluster.yaml
  config/samples/clusterinventory_v1_gardenercluster.yaml
  config/samples/kustomization.yaml
  internal/controller/cluster_controller.go
Labels: lgtm, size/L

#43 Adds default labels and project to feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: size/XS, area/ci, lgtm

#44 Update feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: size/XS, area/ci, lgtm

#45 Issue template
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: size/XS, area/ci, lgtm

#41 adds configuration for protecode and whitesource scanning
  sec-scanners-config.yaml
Labels: kind/feature, area/control-plane, size/XS, lgtm

#38 Run tests on all prs + gitignore enhancement
  .github/workflows/run-tests.yaml
  .gitignore
Labels: kind/feature, area/control-plane, area/ci, size/S, lgtm

#37 Infrastructure Manager creates secrets when a new Gardener Cluster CR is created.
  Dockerfile
  api/v1/gardenercluster_types.go
  api/v1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/infrastructuremanager.kyma-project.io_gardenerclusters.yaml
  go.mod
  go.sum
  internal/controller/cluster_controller.go
  internal/controller/gardener_cluster_controller.go
  internal/controller/gardener_cluster_controller_test.go
  internal/controller/mocks/KubeconfigProvider.go
  internal/controller/suite_test.go
  internal/gardener/KubeConfigProvider.go
Labels: kind/feature, area/control-plane, size/XL, lgtm

#42 Pass configuration parameters to the Infrastructure Manager
  Makefile
  PROJECT
  README.md
  cmd/main.go
  config/crd/bases/clusterinventory.kyma-project.io_clusterinventories.yaml
  config/crd/bases/clusterinventory.kyma-project.io_clusters.yaml
  config/crd/bases/infrastructuremanager.kyma-project.io_clusters.yaml
  config/default/kustomization.yaml
  config/default/manager_gardener_secret_patch.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/gardener_cluster_controller.go
  internal/gardener/client.go
Labels: lgtm, size/L

#39 Infrastructure Manager removes secrets when Gardener Cluster CR is deleted
  internal/controller/gardener_cluster_controller.go
  internal/controller/gardener_cluster_controller_test.go
Labels: kind/feature, area/control-plane, lgtm, size/M
