Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2024-07, with the labels that each got.

#281 Implement Runtime CR deletion handling
  .github/workflows/run-vuln-check.yaml
  Dockerfile
  api/v1/runtime_types.go
  go.mod
  internal/controller/runtime/fsm/runtime_fsm_delete_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_delete_shoot_test.go
  internal/controller/runtime/fsm/runtime_fsm_initialise.go
  internal/controller/runtime/runtime_controller.go
  internal/gardener/client.go
  internal/gardener/mocks/ShootClient.go
Labels: area/ci, lgtm, size/L, cla: yes

#291 Change delete Runtime CR to wait on Shoot CR delete
  config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
  internal/controller/runtime/fsm/runtime_fsm_common.go
  internal/controller/runtime/fsm/runtime_fsm_initialise.go
Labels: lgtm, size/M, cla: yes

#275 feat: KIM - Implementation of update shoot functionality
  api/v1/runtime_types.go
  cmd/main.go
  go.mod
  internal/controller/runtime/fsm/runtime_fsm.go
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_delete_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_initialise.go
  internal/controller/runtime/fsm/runtime_fsm_initialise_test.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_prepare_cluster.go
  internal/controller/runtime/fsm/runtime_fsm_process_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_select_shoot_processing.go
  internal/controller/runtime/fsm/runtime_fsm_select_shoot_processing_test.go
  internal/controller/runtime/fsm/runtime_fsm_take_snapshot.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
  internal/controller/runtime/runtime_controller.go
  internal/controller/runtime/runtime_controller_test.go
  internal/controller/runtime/suite_test.go
  internal/controller/runtime/test_client_obj_tracker.go
Labels: kind/feature, area/control-plane, size/XL, area/ci, lgtm, cla: yes

#271 gardenercluster controller timeout
  cmd/main.go
  config/default/manager_gardener_secret_patch.yaml
  docs/README.md
  hack/runtime-migrator/main.go
  internal/controller/kubeconfig/gardener_cluster_controller.go
  internal/controller/kubeconfig/gardener_cluster_controller_test.go
  internal/controller/kubeconfig/suite_test.go
  internal/gardener/kubeconfig/Provider.go
Labels: area/documentation, lgtm, size/M, cla: yes

#294 fix: Update the Controller Tools Version
  Makefile
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/infrastructuremanager.kyma-project.io_gardenerclusters.yaml
  config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
Labels: lgtm, size/L, cla: yes

#292 feat: Parametrize gardener shoot converter configuration
  api/v1/runtime_types.go
  cmd/main.go
  config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
  config/manager/converter_config.yaml
  config/manager/kustomization.yaml
  go.mod
  go.sum
  hack/converter_config.json
  internal/controller/runtime/fsm/runtime_fsm.go
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/gardener/shoot/converter.go
  internal/gardener/shoot/converter_test.go
Labels: lgtm, size/L, cla: yes

#293 feat: Creating Gardener Cluster CR as part of cluster provisioning
  api/v1/runtime_types.go
  internal/controller/runtime/fsm/runtime_fsm.go
  internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig.go
  internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig_test.go
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
  internal/controller/runtime/runtime_controller_test.go
  internal/controller/runtime/suite_test.go
  internal/gardener/shoot/converter_test.go
Labels: lgtm, size/L, cla: yes

#301 switches to shoot-name label instead of shootName
  api/v1/runtime_types.go
Labels: size/XS, lgtm, cla: yes

#287 feat: First version of shoot comparison app
  hack/shoot-comparator/README.md
  hack/shoot-comparator/cmd/comparator/comparator.go
  hack/shoot-comparator/cmd/comparator/directories.go
  hack/shoot-comparator/cmd/comparator/files.go
  hack/shoot-comparator/cmd/main.go
  hack/shoot-comparator/go.mod
  hack/shoot-comparator/go.sum
  hack/shoot-comparator/internal/directories/direcotries_comparator.go
  hack/shoot-comparator/internal/files/files_comparator.go
  hack/shoot-comparator/pkg/shoot/matcher.go
  hack/shoot-comparator/pkg/shoot/matcher_test.go
  hack/shoot-comparator/pkg/shoot/suite_test.go
Labels: lgtm, size/L, cla: yes

#309 Fix invalid Dockerfile path in shoot-comparator workflow
  .github/workflows/build_shoot_compare.yml
Labels: size/XS, area/ci, lgtm, cla: yes

#307 Renames persist-shoot to dump-shoot-spec
  cmd/main.go
  docs/README.md
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot_test.go
Labels: area/documentation, size/S, lgtm, cla: yes

#298 Add provision killswitch
  api/v1/runtime_types.go
  api/v1/runtime_types_test.go
  cmd/main.go
  docs/README.md
  internal/controller/runtime/fsm/runtime_fsm_create_shoot_dry_run.go
  internal/controller/runtime/fsm/runtime_fsm_initialise.go
  internal/controller/runtime/fsm/runtime_fsm_initialise_test.go
  internal/controller/runtime/runtime_controller.go
  internal/controller/runtime/runtime_controller_test.go
Labels: area/documentation, lgtm, size/L, cla: yes

#316 disables sshAccess by default
  internal/gardener/shoot/extender/provider.go
  internal/gardener/shoot/extender/provider_test.go
Labels: size/S, lgtm, cla: yes

#306 Dockerfile for shoot comparison test app
  Dockerfile
  hack/shoot-comparator/Dockerfile
  hack/shoot-comparator/README.md
Labels: area/ci, lgtm, size/M, cla: yes

#315 adds extender with tolerations for ksa region
  internal/gardener/shoot/converter.go
  internal/gardener/shoot/extender/tolerations.go
  internal/gardener/shoot/extender/tolerations_test.go
Labels: lgtm, size/M, cla: yes

#317 adds CertConfig extender
  internal/gardener/shoot/converter.go
  internal/gardener/shoot/extender/cert_config.go
  internal/gardener/shoot/extender/cert_config_test.go
Labels: lgtm, size/M, cla: yes

#319 Maintenance extender
  config/manager/converter_config.yaml
  converter_config.json
  internal/controller/runtime/fsm/runtime_fsm_delete_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/suite_test.go
  internal/gardener/shoot/converter.go
  internal/gardener/shoot/converter_test.go
  internal/gardener/shoot/extender/exposure_classname_extender.go
  internal/gardener/shoot/extender/kubernetes_version_test.go
  internal/gardener/shoot/extender/maintenance.go
  internal/gardener/shoot/extender/maintenance_test.go
  internal/gardener/shoot/extender/network_filter.go
Labels: lgtm, size/L, cla: yes
