Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2024-10, with the labels that each got.

#404 Change invalid `shoot-comparator` module name
  hack/shoot-comparator/cmd/comparator/directories.go
  hack/shoot-comparator/cmd/comparator/files.go
  hack/shoot-comparator/cmd/main.go
  hack/shoot-comparator/go.mod
  hack/shoot-comparator/internal/directories/comparator.go
  hack/shoot-comparator/internal/files/comparator.go
Labels: size/S, lgtm, cla: yes

#409 Remove worker zones sorting
  internal/gardener/shoot/extender/provider.go
Labels: size/XS, lgtm, cla: yes

#413 Add raw extension comparator
  hack/shoot-comparator/pkg/errors/errors.go
  hack/shoot-comparator/pkg/runtime/raw_extension_matcher.go
  hack/shoot-comparator/pkg/runtime/raw_extension_matcher_test.go
  hack/shoot-comparator/pkg/runtime/testdata/infra_cfg_azure_11.yaml
  hack/shoot-comparator/pkg/runtime/testdata/infra_cfg_azure_12.yaml
  hack/shoot-comparator/pkg/runtime/testdata/infra_cfg_azure_21.yaml
  hack/shoot-comparator/pkg/runtime/testdata/infra_cfg_openstack_11.yaml
  hack/shoot-comparator/pkg/shoot/extensionmatcher.go
  hack/shoot-comparator/pkg/shoot/matcher.go
  hack/shoot-comparator/pkg/shoot/provider_matcher.go
  hack/shoot-comparator/pkg/utilz/utilz.go
Labels: lgtm, size/L, cla: yes

#422 Update some dependencies to latest versions
  go.mod
  go.sum
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc_test.go
  internal/controller/runtime/runtime_controller_test.go
  internal/controller/runtime/suite_test.go
  internal/gardener/shoot/extender/cloud_profile.go
  internal/gardener/shoot/extender/cloud_profile_test.go
Labels: lgtm, size/L, cla: yes

#418 Fix shoot matcher
  hack/shoot-comparator/pkg/runtime/raw_extension_matcher.go
  hack/shoot-comparator/pkg/shoot/matcher.go
  hack/shoot-comparator/pkg/shoot/matcher_test.go
  hack/shoot-comparator/pkg/shoot/provider_matcher.go
  hack/shoot-comparator/pkg/utilz/utilz.go
Labels: size/XXL, lgtm, cla: yes

#421 [QG][KIM] Application that generates loads by creating or deleting Runtime CR
  hack/performance/README.md
  hack/performance/action/worker.go
  hack/performance/cmd/cmd.go
  hack/performance/go.mod
  hack/performance/go.sum
  hack/performance/main.go
Labels: size/XL, lgtm, cla: yes

#423 Converter moved to the pkg folder
  Dockerfile
  cmd/main.go
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_select_shoot_processing.go
  internal/controller/runtime/suite_test.go
  pkg/gardener/client.go
  pkg/gardener/kubeconfig/Provider.go
  pkg/gardener/mocks/ShootClient.go
  pkg/gardener/shoot/converter.go
  pkg/gardener/shoot/converter_test.go
  pkg/gardener/shoot/extender/annotations.go
  pkg/gardener/shoot/extender/annotations_test.go
  pkg/gardener/shoot/extender/cert_config.go
  pkg/gardener/shoot/extender/cert_config_test.go
  pkg/gardener/shoot/extender/cloud_profile.go
  pkg/gardener/shoot/extender/cloud_profile_test.go
  pkg/gardener/shoot/extender/dns.go
  pkg/gardener/shoot/extender/dns_test.go
  pkg/gardener/shoot/extender/exposure_classname_extender.go
  pkg/gardener/shoot/extender/exposure_classname_extender_test.go
  pkg/gardener/shoot/extender/kubernetes.go
  pkg/gardener/shoot/extender/kubernetes_test.go
  pkg/gardener/shoot/extender/labels.go
  pkg/gardener/shoot/extender/labels_test.go
  pkg/gardener/shoot/extender/maintenance.go
  pkg/gardener/shoot/extender/maintenance_test.go
  pkg/gardener/shoot/extender/network_filter.go
  pkg/gardener/shoot/extender/network_filter_test.go
  pkg/gardener/shoot/extender/oidc.go
  pkg/gardener/shoot/extender/oidc_test.go
  pkg/gardener/shoot/extender/provider.go
  pkg/gardener/shoot/extender/provider_test.go
  pkg/gardener/shoot/extender/tolerations.go
  pkg/gardener/shoot/extender/tolerations_test.go
  pkg/gardener/shoot/hyperscaler/aws/config.go
  pkg/gardener/shoot/hyperscaler/aws/config_test.go
  pkg/gardener/shoot/hyperscaler/aws/zones.go
  pkg/gardener/shoot/hyperscaler/azure/config.go
  pkg/gardener/shoot/hyperscaler/azure/config_test.go
  pkg/gardener/shoot/hyperscaler/azure/model.go
  pkg/gardener/shoot/hyperscaler/azure/zones.go
  pkg/gardener/shoot/hyperscaler/const.go
  pkg/gardener/shoot/hyperscaler/gcp/config.go
  pkg/gardener/shoot/hyperscaler/gcp/config_test.go
  pkg/gardener/shoot/hyperscaler/openstack/config.go
  pkg/gardener/shoot/hyperscaler/openstack/config_test.go
Labels: lgtm, size/M, cla: yes

#424 Config file package moved to pkg folder
  cmd/main.go
  internal/controller/runtime/fsm/runtime_fsm.go
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc.go
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc_test.go
  internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig_test.go
  internal/controller/runtime/fsm/runtime_fsm_initialise_test.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot_test.go
  internal/controller/runtime/fsm/utilz_for_test.go
  internal/controller/runtime/suite_test.go
  pkg/config/config.go
  pkg/gardener/shoot/converter.go
  pkg/gardener/shoot/converter_test.go
  pkg/gardener/shoot/extender/oidc.go
  pkg/gardener/shoot/extender/oidc_test.go
Labels: lgtm, size/M, cla: yes

#429 removes docs and configs for removed runtime-reconciler-enabled flag
  config/default/manager_gardener_secret_patch.yaml
  docs/README.md
Labels: area/documentation, size/XS, lgtm, cla: yes

#431 Implemented changes in DNS extender
  pkg/gardener/shoot/extender/dns.go
  pkg/gardener/shoot/extender/dns_test.go
Labels: lgtm, size/M, cla: yes

#430 Fine tune shoot matcher
  config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/go.sum
  hack/shoot-comparator/pkg/runtime/raw_extension_matcher.go
  hack/shoot-comparator/pkg/shoot/matcher.go
Labels: lgtm, size/M, cla: yes

#437 Fixed regression in Comparator tests
  hack/shoot-comparator/pkg/shoot/matcher.go
  hack/shoot-comparator/pkg/shoot/matcher_test.go
Labels: size/S, lgtm, cla: yes

#436 Fixed issue with enabling network filter extension
  pkg/gardener/shoot/extender/network_filter.go
  pkg/gardener/shoot/extender/network_filter_test.go
Labels: lgtm, size/M, cla: yes

#434 Add latest tag on main
  .github/workflows/build_kim.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#439 fix failing trivy job
  .github/workflows/build_kim.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#441 fix yaml error
  .github/workflows/build_kim.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#440 Proposal to reset runtime metric on application startup
  cmd/main.go
  internal/controller/metrics/metrics.go
  internal/controller/metrics/mocks/Metrics.go
Labels: size/S, do-not-merge/hold, cla: yes

#433 switches daily-markdown-link-check action to a concrete sha version
  .github/workflows/daily-markdown-link-check.yaml
Labels: size/XS, area/ci, cla: yes

#448 Update runtime state metrics on application startup
  cmd/main.go
  internal/controller/metrics/metrics.go
  internal/controller/metrics/mocks/Metrics.go
  internal/controller/runtime/fsm/runtime_fsm_apply_crb_test.go
  internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig_test.go
  internal/controller/runtime/fsm/runtime_fsm_initialise.go
  internal/controller/runtime/fsm/runtime_fsm_initialise_test.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot_test.go
  internal/controller/runtime/suite_test.go
Labels: lgtm, size/M, cla: yes

#452 Fix latest label
  .github/workflows/build_kim.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#453 Fix latest tag
  .github/workflows/build_kim.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#425 Migrator dependencies updated
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/go.sum
  hack/runtime-migrator/internal/config.go
  hack/runtime-migrator/main.go
  hack/shoot-comparator/pkg/shoot/matcher.go
Labels: lgtm, size/L, cla: yes

#461 Fix latest tag
  .github/workflows/build_kim.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#462 switches pr-markdown-link-check version to whitelisted one
  .github/workflows/pr-markdown-link-check.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#465 Fix latest
  .github/workflows/build_kim.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#466 Use single quotes
  .github/workflows/build_kim.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#450 Migrator refactor
  hack/runtime-migrator/cmd/main.go
  hack/runtime-migrator/cmd/migration.go
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/go.sum
  hack/runtime-migrator/internal/comparator/comparator.go
  hack/runtime-migrator/internal/comparator/report.go
  hack/runtime-migrator/internal/config/config.go
  hack/runtime-migrator/internal/migration/output.go
  hack/runtime-migrator/internal/migration/results.go
  hack/runtime-migrator/internal/result.go
  hack/runtime-migrator/internal/runtime/migrator.go
  hack/runtime-migrator/internal/runtime/verifier.go
  hack/runtime-migrator/main.go
Labels: size/XXL, lgtm, cla: yes

#471 removes outdated converter_config example
  config/manager/converter_config.yaml
Labels: size/S, lgtm, cla: yes

#469 oidc state complition does not make the runtime CR as ready
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc.go
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc_test.go
Labels: size/XS, lgtm, cla: yes

#454 Preserve shoot InfrastructureConfig data during migration inside RuntimeCR
  api/v1/runtime_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
  hack/runtime-migrator/go.sum
  hack/runtime-migrator/internal/runtime/migrator.go
  pkg/gardener/shoot/extender/provider.go
Labels: lgtm, size/M, cla: yes

#468 KIM State machine fix - only allow to enter into waiting state when cluster CR is in pending state
  internal/controller/runtime/fsm/runtime_fsm_initialise.go
  internal/controller/runtime/fsm/runtime_fsm_select_shoot_processing.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
Labels: kind/bug, area/control-plane, lgtm, size/M, cla: yes
