Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2024-12, with the labels that each got.

#539 Fix logging shoot name
  internal/controller/runtime/runtime_controller.go
Labels: size/XS, lgtm, cla: yes

#531 Rbac least priviligates
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  internal/controller/kubeconfig/gardener_cluster_controller.go
  internal/controller/runtime/runtime_controller.go
Labels: lgtm, size/M, cla: yes

#545 bumps kustomize from v4.5.5 to v5.5.0
  Makefile
Labels: size/XS, lgtm, cla: yes

#551 Handing missing Disabled field in OIDC extension data to avoid crash
  hack/runtime-migrator/internal/runtime/migrator.go
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc.go
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc_test.go
Labels: lgtm, size/M, cla: yes

#554 Kim should not delete existing service accounts
  internal/controller/runtime/fsm/runtime_fsm_apply_clusterrolebindings.go
  internal/controller/runtime/fsm/runtime_fsm_apply_crb_test.go
Labels: lgtm, size/M, cla: yes

#555 Fix bug causing crb removal
  internal/controller/runtime/fsm/runtime_fsm_apply_clusterrolebindings.go
  internal/controller/runtime/fsm/runtime_fsm_apply_crb_test.go
Labels: lgtm, size/M, cla: yes

#560 Configurable number of workers for both controllers with default value 25
  cmd/main.go
  docs/README.md
  internal/controller/kubeconfig/gardener_cluster_controller.go
  internal/controller/kubeconfig/suite_test.go
  internal/controller/runtime/runtime_controller.go
  internal/controller/runtime/suite_test.go
Labels: area/documentation, lgtm, size/M, cla: yes

#562 Fix ExtensionsExtender to generate auditlog extension only if auditlog data exists
  pkg/gardener/shoot/converter.go
  pkg/gardener/shoot/converter_test.go
  pkg/gardener/shoot/extender/extensions/extender.go
  pkg/gardener/shoot/extender/extensions/extensions_extender_test.go
Labels: lgtm, size/L, cla: yes

#563 KIM Migrator - RBAC migration code updates
  hack/runtime-migrator/cmd/migration.go
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/internal/runtime/migrator.go
  hack/runtime-migrator/internal/runtime/migrator_test.go
Labels: lgtm, size/L, cla: yes

#574 requeue when oidc cr creation fails
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc.go
Labels: size/XS, lgtm, cla: yes

#577 replaces golang.org/x/net to v0.33.0
  go.mod
  go.sum
  hack/performance/go.mod
  hack/performance/go.sum
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/go.sum
  hack/shoot-comparator/go.mod
  hack/shoot-comparator/go.sum
Labels: lgtm, size/L, cla: yes

#572 Refactor migration tool to introduce backup-restore functionality
  hack/runtime-migrator/README-rb.md
  hack/runtime-migrator/README-rm.md
  hack/runtime-migrator/README-rr.md
  hack/runtime-migrator/README.md
  hack/runtime-migrator/cmd/backup/main.go
  hack/runtime-migrator/cmd/migration/main.go
  hack/runtime-migrator/cmd/migration/migration.go
  hack/runtime-migrator/cmd/restore/main.go
  hack/runtime-migrator/input/runtimeids_sample.txt
  hack/runtime-migrator/internal/config/client.go
  hack/runtime-migrator/internal/config/input.go
  hack/runtime-migrator/internal/migration/migrator.go
  hack/runtime-migrator/internal/migration/migrator_test.go
  hack/runtime-migrator/internal/migration/output.go
  hack/runtime-migrator/internal/migration/verifier.go
  hack/shoot-comparator/README.md
  hack/shoot-comparator/scripts/README.md
Labels: size/XL, lgtm, cla: yes
