Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2024-05, with the labels that each got.

#203 Add runtime crd and controller
  Dockerfile
  Makefile
  PROJECT
  api/v1/runtime_types.go
  api/v1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
  config/crd/kustomization.yaml
  config/infrastructuremanager.kyma-project.io_gardenerclusters.yaml
  config/infrastructuremanager.kyma-project.io_runtimes.yaml
  config/rbac/role.yaml
  config/rbac/runtime_editor_role.yaml
  config/rbac/runtime_viewer_role.yaml
  config/samples/infrastructuremanager_v1_runtime.yaml
  config/samples/kustomization.yaml
  go.mod
  internal/controller/runtime_controller.go
  internal/controller/runtime_controller_test.go
Labels: size/XXL, lgtm, cla: yes

#210 Adjusted to the newest version of contract
  api/v1/runtime_types.go
  api/v1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
  internal/controller/runtime_controller_test.go
  internal/gardener/kubeconfig/Provider.go
  internal/gardener/shoot/converter.go
Labels: size/XXL, lgtm, cla: yes

#218 Adjust to the contract changes
  api/v1/runtime_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
  internal/controller/runtime_controller_test.go
  internal/gardener/shoot/converter.go
Labels: lgtm, size/M, cla: yes

#221 Implement basic structures of the shoot converters
  internal/gardener/shoot/converter.go
  internal/gardener/shoot/converter_test.go
  internal/gardener/shoot/extender/annotations.go
  internal/gardener/shoot/extender/dns.go
  internal/gardener/shoot/extender/dns_test.go
  internal/gardener/shoot/extender/extender.go
  internal/gardener/shoot/extender/kubernetes.go
  internal/gardener/shoot/extender/kubernetes_test.go
  internal/gardener/shoot/extender/networking.go
  internal/gardener/shoot/extender/networking_test.go
  internal/gardener/shoot/extender/provider.go
  internal/gardener/shoot/extender/provider_test.go
  internal/gardener/shoot/hyperscaler/aws/provider_specific_config.go
  internal/gardener/shoot/hyperscaler/azure/providerspecificconfig.go
  internal/gardener/shoot/hyperscaler/gcp/providerspecificconfig.go
  internal/gardener/shoot/hyperscaler/sapconvergedcloud/providerspecificconfig.go
Labels: size/XL, lgtm, cla: yes

#220 Add shoot matcher
  go.mod
  internal/testing/shoot/matcher.go
  internal/testing/shoot/matcher_test.go
  internal/testing/shoot/suite_test.go
Labels: lgtm, size/L, cla: yes

#202 Added ADR for the provisioning functionality in KIM
  docs/adr/001-provisioning.md
  docs/adr/README.md
  docs/adr/assets/keb-kim-target-arch.drawio.svg
  docs/adr/assets/runtime-examples/aws-freemium.yaml
  docs/adr/assets/runtime-examples/aws-minimal.yaml
  docs/adr/assets/runtime-examples/aws-trial.yaml
  docs/adr/assets/runtime-examples/aws.yaml
  docs/adr/assets/runtime-examples/azure-fremium.yaml
  docs/adr/assets/runtime-examples/azure-lite.yaml
  docs/adr/assets/runtime-examples/azure.yaml
  docs/adr/assets/runtime-examples/gcp.yaml
  docs/adr/assets/runtime-examples/sap-converged-cloud.yaml
Labels: size/XXL, area/documentation, lgtm, cla: yes

#222 Add AWS provider specific config to the shoot converter
  .gitignore
  internal/gardener/shoot/converter.go
  internal/gardener/shoot/converter_test.go
  internal/gardener/shoot/extender/provider.go
  internal/gardener/shoot/extender/provider_test.go
  internal/gardener/shoot/hyperscaler/aws/model.go
  internal/gardener/shoot/hyperscaler/aws/provider_specific_config.go
  internal/gardener/shoot/hyperscaler/aws/provider_specific_config_test.go
  internal/gardener/shoot/hyperscaler/aws/zones.go
Labels: size/XL, lgtm, cla: yes

#227 Added feature flag that controls provisioning
  cmd/main.go
  config/default/manager_gardener_secret_patch.yaml
  docs/README.md
  internal/controller/runtime_controller.go
Labels: area/documentation, lgtm, size/M, cla: yes

#228 Add Azure provider specific config
  docs/adr/assets/runtime-examples/azure-fremium.yaml
  docs/adr/assets/runtime-examples/azure-lite.yaml
  docs/adr/assets/runtime-examples/azure.yaml
  internal/gardener/shoot/extender/provider.go
  internal/gardener/shoot/hyperscaler/azure/model.go
  internal/gardener/shoot/hyperscaler/azure/provider_specific_config_test.go
  internal/gardener/shoot/hyperscaler/azure/providerspecificconfig.go
  internal/gardener/shoot/hyperscaler/azure/zones.go
Labels: area/documentation, lgtm, size/L, cla: yes

#205 runtimes migrator
  .github/workflows/golangci-lint.yaml
  .github/workflows/run-tests.yaml
  .github/workflows/run-vuln-check.yaml
  .golangci.yaml
  hack/runtime-migrator/README.md
  hack/runtime-migrator/input/runtimeids_sample.json
  hack/runtime-migrator/internal/config.go
  hack/runtime-migrator/internal/result.go
  hack/runtime-migrator/main.go
Labels: size/XL, area/ci, lgtm, cla: yes

#233 naive provisioning
  api/v1/runtime_types.go
  cmd/main.go
  config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
  go.mod
  go.sum
  internal/controller/runtime_controller.go
  internal/controller/runtime_controller_test.go
  internal/controller/suite_test.go
  internal/gardener/shoot/converter.go
  internal/gardener/shoot/extender/networking.go
Labels: lgtm, size/L, cla: yes

#238 RuntimeID instead of shootname used for Runtime CR name
  hack/runtime-migrator/main.go
Labels: size/XS, lgtm, cla: yes

#239 fixes misformated code section
  hack/runtime-migrator/README.md
Labels: size/XS, lgtm, cla: yes
