Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2024-08, with the labels that each got.

#310 Compare directories in the shoot_comparator tool
  hack/shoot-comparator/README.md
  hack/shoot-comparator/cmd/comparator/directories.go
  hack/shoot-comparator/go.mod
  hack/shoot-comparator/go.sum
  hack/shoot-comparator/internal/directories/comparator.go
  hack/shoot-comparator/internal/directories/comparator_test.go
  hack/shoot-comparator/internal/directories/direcotries_comparator.go
  hack/shoot-comparator/internal/directories/report.go
  hack/shoot-comparator/internal/files/comparator.go
Labels: size/XL, lgtm, cla: yes

#322 Fixes for making shoot comparison easier
  hack/shoot-comparator/pkg/shoot/matcher.go
  hack/shoot-comparator/pkg/shoot/matcher_test.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot_test.go
  internal/controller/runtime/fsm/testing/shoot.go
  internal/controller/runtime/fsm/utilz_for_test.go
Labels: lgtm, size/L, cla: yes

#318 feat: Adding state to delete Kubeconfig/GardenerCluster CR object
  api/v1/runtime_types.go
  internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig.go
  internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig_test.go
  internal/controller/runtime/fsm/runtime_fsm_delete_kubeconfig.go
  internal/controller/runtime/fsm/runtime_fsm_delete_kubeconfig_test.go
  internal/controller/runtime/fsm/runtime_fsm_delete_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_initialise.go
  internal/controller/runtime/fsm/runtime_fsm_initialise_test.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
  internal/controller/runtime/runtime_controller_test.go
  internal/controller/runtime/suite_test.go
  internal/controller/runtime/test_client_obj_tracker.go
Labels: size/XL, lgtm, cla: yes

#321 Add job that executes shoot comparison
  hack/shoot-comparator/scripts/README.md
  hack/shoot-comparator/scripts/cleanup-comparison-resources.sh
  hack/shoot-comparator/scripts/fetch_shoots_for_provisioner_and_kim.sh
  hack/shoot-comparator/scripts/manifests/fetch-kim-and-provisioner-files.yaml
  hack/shoot-comparator/scripts/manifests/fetch-results-pod.yaml
  hack/shoot-comparator/scripts/manifests/job.yaml
  hack/shoot-comparator/scripts/manifests/snapshot-for-comparison.yaml
  hack/shoot-comparator/scripts/run_comparison.sh
Labels: lgtm, size/L, cla: yes

#336 Align KIM to use Config Map with converter config
  cmd/main.go
  config/default/kustomization.yaml
  config/default/manager_converter_config_patch.yaml
  config/manager/converter_config.yaml
Labels: lgtm, size/M, cla: yes

#323 Add kubeconfig access handling
  cmd/main.go
  internal/controller/runtime/fsm/runtime_fsm_apply_clusterrolebindings.go
  internal/controller/runtime/fsm/runtime_fsm_apply_crb_test.go
  internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig.go
  internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig_test.go
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_process_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
  internal/controller/runtime/fsm/utilz_for_test.go
  internal/controller/runtime/runtime_controller_test.go
  internal/controller/runtime/suite_test.go
Labels: size/XL, lgtm, cla: yes

#329 Fixes to make migrator up to date
  api/v1/runtime_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
  hack/runtime-migrator/input/runtimeids_sample.json
  hack/runtime-migrator/main.go
  hack/shoot-comparator/go.mod
  hack/shoot-comparator/pkg/shoot/extensionmatcher.go
  hack/shoot-comparator/pkg/shoot/extensionmatcher_test.go
  hack/shoot-comparator/pkg/shoot/matcher.go
  hack/shoot-comparator/scripts/manifests/job.yaml
  internal/gardener/shoot/converter.go
  internal/gardener/shoot/converter_test.go
Labels: lgtm, size/L, cla: yes

#345 Runtime CR examples updated
  docs/adr/assets/runtime-examples/aws-freemium.yaml
  docs/adr/assets/runtime-examples/aws-minimal.yaml
  docs/adr/assets/runtime-examples/aws-trial.yaml
  docs/adr/assets/runtime-examples/aws.yaml
  docs/adr/assets/runtime-examples/azure-fremium.yaml
  docs/adr/assets/runtime-examples/azure-lite.yaml
  docs/adr/assets/runtime-examples/azure.yaml
  docs/adr/assets/runtime-examples/gcp.yaml
  docs/adr/assets/runtime-examples/sap-converged-cloud.yaml
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_delete_kubeconfig.go
Labels: area/documentation, lgtm, size/L, cla: yes

#354 Removes bearerTokenFile and tlsConfig from prometheus service monitor
  config/prometheus/monitor.yaml
Labels: size/XS, lgtm, cla: yes
