Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2024-11, with the labels that each got.

#476 creates NamedResourceReference for DNS secret
  pkg/gardener/shoot/extender/dns.go
  pkg/gardener/shoot/extender/dns_test.go
Labels: size/S, lgtm, cla: yes

#474 Final fixes in the migrator
  hack/runtime-migrator/README.md
  hack/runtime-migrator/cmd/migration.go
  hack/runtime-migrator/internal/migration/results.go
Labels: lgtm, size/L, cla: yes

#472 New audit log extenders
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_create_shoot_dry_run.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot.go
  internal/controller/runtime/suite_test.go
  pkg/gardener/shoot/converter.go
  pkg/gardener/shoot/converter_test.go
  pkg/gardener/shoot/extender/auditlogs/extender.go
  pkg/gardener/shoot/extender/auditlogs/extender_test.go
  pkg/gardener/shoot/extender/auditlogs/set_extension.go
  pkg/gardener/shoot/extender/auditlogs/set_extension_test.go
  pkg/gardener/shoot/extender/auditlogs/set_policy_configmap.go
  pkg/gardener/shoot/extender/auditlogs/set_policy_configmap_test.go
  pkg/gardener/shoot/extender/auditlogs/set_secret.go
  pkg/gardener/shoot/extender/auditlogs/set_secret_test.go
Labels: lgtm, size/L, cla: yes

#478 Remove reuse/dep5 as depreceated
  .reuse/dep5
  REUSE.toml
Labels: lgtm, size/M, cla: yes

#479 zones are taken from the existing shoot for patch operation
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_delete_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/suite_test.go
  pkg/gardener/shoot/converter.go
  pkg/gardener/shoot/converter_test.go
  pkg/gardener/shoot/extender/provider.go
  pkg/gardener/shoot/extender/provider_test.go
Labels: lgtm, size/L, cla: yes

#481 removes trivy
  .github/workflows/build_kim.yaml
Labels: area/ci, size/M, cla: yes

#484 Fixed logging issue
  internal/controller/runtime/fsm/runtime_fsm_delete_shoot.go
Labels: size/XS, lgtm, cla: yes

#485 Fix for deleting shoot - adding additional fields
  internal/controller/runtime/fsm/runtime_fsm_delete_shoot.go
Labels: size/XS, lgtm, cla: yes

#477 Fix auditlogs switch impl
  api/v1/runtime_types.go
  cmd/main.go
  internal/auditlogging/auditlogging.go
  internal/auditlogging/mocks/AuditLogConfigurator.go
  internal/auditlogging/mocks/AuditLogging.go
  internal/auditlogging/tests/auditlogging_test.go
  internal/controller/runtime/fsm/runtime_fsm.go
  internal/controller/runtime/fsm/runtime_fsm_apply_clusterrolebindings.go
  internal/controller/runtime/fsm/runtime_fsm_apply_crb_test.go
  internal/controller/runtime/fsm/runtime_fsm_configure_auditlog.go
  internal/controller/runtime/fsm/runtime_fsm_configure_auditlog_test.go
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc.go
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc_test.go
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_create_shoot_dry_run.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot.go
  internal/controller/runtime/fsm/utilz_for_test.go
  internal/controller/runtime/runtime_controller.go
  internal/controller/runtime/runtime_controller_test.go
  internal/controller/runtime/suite_test.go
  internal/controller/runtime/test_client_obj_tracker.go
  internal/controller/runtime/test_client_obj_tracker_test.go
  pkg/gardener/shoot/converter.go
  pkg/gardener/shoot/converter_test.go
  pkg/gardener/shoot/extender/auditlogs/auditlogs_configuration.go
  pkg/gardener/shoot/extender/auditlogs/auditlogs_configuration_test.go
  pkg/gardener/shoot/extender/auditlogs/set_extension.go
Labels: size/XXL, lgtm, cla: yes

#482 dependabot 08 11 2024
  Makefile
  config/crd/bases/infrastructuremanager.kyma-project.io_gardenerclusters.yaml
  config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
  go.mod
  go.sum
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/go.sum
  internal/controller/runtime/test_client_obj_tracker.go
Labels: lgtm, size/L, cla: yes

#483 Protection of current versions of machine image and Kubernetes during shoot "Patch" operation
  go.mod
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/go.sum
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  pkg/gardener/shoot/converter.go
  pkg/gardener/shoot/converter_test.go
  pkg/gardener/shoot/extender/kubernetes.go
  pkg/gardener/shoot/extender/kubernetes_test.go
  pkg/gardener/shoot/extender/provider.go
  pkg/gardener/shoot/extender/provider_test.go
Labels: size/XL, lgtm, cla: yes

#486 WIP: Adjust migrator to audit log related changes
  hack/runtime-migrator/cmd/main.go
  hack/runtime-migrator/cmd/migration.go
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/go.sum
  hack/runtime-migrator/internal/config/config.go
  hack/runtime-migrator/internal/runtime/migrator.go
  hack/runtime-migrator/internal/runtime/verifier.go
Labels: lgtm, size/L, cla: yes

#487 fix issue with migrator's timeout
  hack/runtime-migrator/cmd/main.go
  hack/runtime-migrator/cmd/migration.go
Labels: lgtm, size/M, cla: yes

#480 Improves gardener errors handling for those which can be retried
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/go.sum
  internal/controller/runtime/fsm/runtime_fsm_apply_clusterrolebindings.go
  internal/controller/runtime/fsm/runtime_fsm_select_shoot_processing.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
  pkg/gardener/gardener_error_handler.go
  pkg/gardener/gardener_error_handler_test.go
Labels: lgtm, size/L, cla: yes

#489 Fixed issue with audit log extension comparison
  hack/runtime-migrator/cmd/migration.go
  hack/shoot-comparator/pkg/runtime/raw_extension_matcher.go
Labels: size/XS, lgtm, cla: yes

#491 Fix shoot converter not to override dns settings
  hack/runtime-migrator/internal/runtime/verifier.go
  hack/shoot-comparator/internal/files/comparator.go
  hack/shoot-comparator/pkg/shoot/matcher.go
  hack/shoot-comparator/pkg/shoot/matcher_test.go
  pkg/gardener/shoot/converter.go
  pkg/gardener/shoot/converter_test.go
Labels: lgtm, size/M, cla: yes

#488 Add new extender to enforce configuration of shoot seed within the same region as the shoot
  internal/controller/runtime/suite_test.go
  pkg/gardener/shoot/converter.go
  pkg/gardener/shoot/extender/auditlogs/auditlogs_configuration_test.go
  pkg/gardener/shoot/extender/provider_test.go
  pkg/gardener/shoot/extender/seed_selector.go
  pkg/gardener/shoot/extender/seed_selector_test.go
Labels: lgtm, size/L, cla: yes

#510 grouping of k8s.io and gardener dependabot PRs
  .github/dependabot.yml
Labels: area/ci, size/S, lgtm, cla: yes

#499 no longer deletes crbs managed by reconciler
  internal/controller/runtime/fsm/runtime_fsm_apply_clusterrolebindings.go
  internal/controller/runtime/fsm/runtime_fsm_apply_crb_test.go
Labels: lgtm, size/M, cla: yes

#516 Fixed timeout issue
  hack/runtime-migrator/README.md
  hack/runtime-migrator/cmd/main.go
  hack/runtime-migrator/cmd/migration.go
  hack/runtime-migrator/input/runtimeids_sample.txt
  hack/runtime-migrator/internal/config/config.go
Labels: lgtm, size/L, cla: yes

#475 Set the number of concurrent reconciles for the Runtime controller to 25
  cmd/main.go
  internal/controller/kubeconfig/gardener_cluster_controller.go
  internal/controller/runtime/fsm/runtime_fsm.go
  internal/controller/runtime/fsm/runtime_fsm_apply_clusterrolebindings.go
  internal/controller/runtime/fsm/runtime_fsm_apply_crb_test.go
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc.go
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc_test.go
  internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig.go
  internal/controller/runtime/fsm/runtime_fsm_delete_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
  internal/controller/runtime/fsm/utilz_for_test.go
  internal/controller/runtime/runtime_controller.go
  internal/controller/runtime/suite_test.go
Labels: lgtm, size/L, cla: yes

#521 Logging runtime ID and shoot name
  cmd/main.go
  hack/runtime-migrator/cmd/main.go
  hack/runtime-migrator/cmd/migration.go
  hack/runtime-migrator/internal/config/config.go
  hack/runtime-migrator/internal/migration/output.go
  hack/runtime-migrator/internal/runtime/migrator.go
  hack/runtime-migrator/internal/runtime/verifier.go
  internal/controller/metrics/mocks/Metrics.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/runtime_controller.go
Labels: lgtm, size/M, cla: yes

#524 Restrict the controller to watch only kcp-system namespace
  cmd/main.go
Labels: size/S, lgtm, cla: yes

#522 Migrator: added fetching shoot to minimise runtime recreation risk
  hack/runtime-migrator/README.md
  hack/runtime-migrator/cmd/main.go
  hack/runtime-migrator/cmd/migration.go
  hack/runtime-migrator/internal/config/config.go
  hack/runtime-migrator/internal/runtime/migrator.go
  hack/shoot-comparator/pkg/shoot/matcher.go
  hack/shoot-comparator/scripts/manifests/job.yaml
Labels: lgtm, size/L, cla: yes

#534 Add gardener cluster recovery for patch operations
  internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig.go
  internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig_test.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
Labels: size/S, lgtm, cla: yes

#532 Set error state, if seed doesn't exist in required region
  api/v1/runtime_types.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
Labels: size/S, lgtm, cla: yes
