Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2024-09, with the labels that each got.

#355 sets readOnlyRootFilesystem flag to true
  config/manager/manager.yaml
Labels: size/XS, lgtm, cla: yes

#361 Adapt tests to auditlogs changes
  internal/controller/runtime/fsm/runtime_fsm_apply_crb_test.go
  internal/controller/runtime/fsm/utilz_for_test.go
Labels: size/XL, lgtm, cla: yes

#365 Waiting for Gardener shoot to be in Ready state after configuring Audit Log
  internal/auditlogging/auditlogging.go
  internal/controller/runtime/fsm/runtime_fsm_apply_crb_test.go
  internal/controller/runtime/fsm/runtime_fsm_configure_auditlog.go
  internal/controller/runtime/fsm/runtime_fsm_configure_auditlog_test.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
  internal/controller/runtime/runtime_controller_test.go
  internal/controller/runtime/suite_test.go
  internal/controller/runtime/testdata/auditConfig.json
Labels: lgtm, size/L, cla: yes

#370 Migrate build pipeline
  .github/workflows/build_kim.yaml
Labels: area/ci, lgtm, size/L, cla: yes

#371 Bump docker image
  Dockerfile
Labels: size/XS, lgtm, cla: yes

#360 OIDC extender
  internal/gardener/shoot/extender/oidc.go
  internal/gardener/shoot/extender/oidc_test.go
Labels: size/S, lgtm, cla: yes

#367 Possibility of disabling audit log functionality per landscape
  api/v1/runtime_types.go
  cmd/main.go
  docs/README.md
  internal/auditlogging/auditlogging.go
  internal/auditlogging/tests/auditlogging_test.go
  internal/controller/runtime/fsm/runtime_fsm.go
  internal/controller/runtime/fsm/runtime_fsm_configure_auditlog.go
  internal/controller/runtime/fsm/runtime_fsm_configure_auditlog_test.go
  internal/gardener/shoot/converter.go
  internal/gardener/shoot/converter_test.go
Labels: area/documentation, lgtm, size/L, cla: yes

#374 Fix GH Action `tests` in KIM
  .github/workflows/run-tests.yaml
Labels: area/ci, size/S, lgtm, cla: yes

#375 Configuration of GH workflows to use go version 1.23.0
  .github/workflows/golangci-lint.yaml
  .github/workflows/run-tests.yaml
  .github/workflows/run-vuln-check.yaml
  go.mod
  hack/shoot-comparator/Dockerfile
  hack/shoot-comparator/go.mod
Labels: area/ci, size/S, lgtm, cla: yes

#377 Fixes to migrator that will remove unimportant differences
  hack/runtime-migrator/main.go
Labels: size/S, lgtm, cla: yes

#379 fixes logger panics
  internal/controller/runtime/fsm/runtime_fsm_configure_auditlog.go
Labels: size/S, lgtm, cla: yes

#378 Handle the Kubernetes conflict error in KIM Audit Log
  internal/auditlogging/auditlogging.go
  internal/controller/runtime/fsm/runtime_fsm_configure_auditlog.go
  internal/controller/runtime/fsm/runtime_fsm_configure_auditlog_test.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go
  internal/controller/runtime/runtime_controller_test.go
Labels: lgtm, size/M, cla: yes

#373 oidc extension added only if controlled-by-provisioner value is disabled
  internal/gardener/shoot/extender/dns_test.go
  internal/gardener/shoot/extender/oidc.go
  internal/gardener/shoot/extender/oidc_test.go
Labels: lgtm, size/L, cla: yes

#380 Align fields with provisioner: Static Kubetoken + Network Filter
  internal/gardener/shoot/converter.go
  internal/gardener/shoot/extender/kubernetes.go
  internal/gardener/shoot/extender/kubernetes_test.go
  internal/gardener/shoot/extender/kubernetes_version.go
  internal/gardener/shoot/extender/network_filter.go
Labels: lgtm, size/M, cla: yes

#376 Refactor in audit log state
  internal/controller/runtime/fsm/runtime_fsm_configure_auditlog.go
Labels: lgtm, size/L, cla: yes

#392 Add worker field to GCP
  internal/gardener/shoot/hyperscaler/gcp/config.go
  internal/gardener/shoot/hyperscaler/gcp/config_test.go
Labels: size/XS, lgtm, cla: yes

#385 Fix dump shoot name
  internal/controller/runtime/fsm/runtime_fsm_create_shoot_dry_run.go
  internal/controller/runtime/fsm/runtime_fsm_initialise.go
  internal/controller/runtime/fsm/runtime_fsm_initialise_test.go
Labels: lgtm, size/L, cla: yes

#389 Update Golang version to 1.23.1
  .github/workflows/golangci-lint.yaml
  .github/workflows/run-tests.yaml
  .github/workflows/run-vuln-check.yaml
  Dockerfile
  go.mod
Labels: area/ci, size/S, lgtm, cla: yes

#394 Fix compare job
  hack/shoot-comparator/cmd/comparator/directories.go
  hack/shoot-comparator/internal/directories/comparator.go
  hack/shoot-comparator/scripts/README.md
  hack/shoot-comparator/scripts/manifests/job.yaml
  hack/shoot-comparator/scripts/manifests/mount-kim-volume-with-write-access.yaml
  hack/shoot-comparator/scripts/manifests/mount-prov-volume-with-write-access.yaml
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot_test.go
Labels: lgtm, size/L, cla: yes

#399 Skip getting shoot if runtime is controlled by the provisioner
  internal/controller/runtime/fsm/runtime_fsm_take_snapshot.go
Labels: size/XS, lgtm, cla: yes
