Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2024-06, with the labels that each got.

#248 Implementation of the converter for provider specific config for GCP
  api/v1/zz_generated.deepcopy.go
  go.mod
  go.sum
  internal/gardener/shoot/extender/provider.go
  internal/gardener/shoot/hyperscaler/aws/config.go
  internal/gardener/shoot/hyperscaler/aws/config_test.go
  internal/gardener/shoot/hyperscaler/azure/config.go
  internal/gardener/shoot/hyperscaler/azure/config_test.go
  internal/gardener/shoot/hyperscaler/gcp/config.go
  internal/gardener/shoot/hyperscaler/gcp/config_test.go
  internal/gardener/shoot/hyperscaler/gcp/providerspecificconfig.go
  internal/gardener/shoot/hyperscaler/sapconvergedcloud/config.go
Labels: lgtm, size/L, cla: yes

#246 oidc config is also migrated to additionalOidcs field + removes not needed shoot labels
  hack/runtime-migrator/main.go
Labels: lgtm, size/M, cla: yes

#249 Implementation of the converter for provider specific config for Open Stack
  go.mod
  go.sum
  internal/gardener/shoot/extender/provider.go
  internal/gardener/shoot/extender/provider_test.go
  internal/gardener/shoot/hyperscaler/aws/config.go
  internal/gardener/shoot/hyperscaler/aws/config_test.go
  internal/gardener/shoot/hyperscaler/aws/model.go
  internal/gardener/shoot/hyperscaler/aws/zones.go
  internal/gardener/shoot/hyperscaler/openstack/config.go
  internal/gardener/shoot/hyperscaler/openstack/config_test.go
Labels: lgtm, size/L, cla: yes

#255 Add missing stuff to the converters
  internal/controller/runtime_controller.go
  internal/gardener/shoot/converter.go
  internal/gardener/shoot/converter_test.go
  internal/gardener/shoot/extender/cloud_profile.go
  internal/gardener/shoot/extender/cloud_profile_test.go
  internal/gardener/shoot/extender/dns.go
  internal/gardener/shoot/extender/dns_test.go
  internal/gardener/shoot/extender/kubernetes.go
  internal/gardener/shoot/extender/kubernetes_version.go
  internal/gardener/shoot/extender/kubernetes_version_test.go
  internal/gardener/shoot/extender/networking.go
  internal/gardener/shoot/extender/networking_test.go
  internal/gardener/shoot/extender/oidc.go
  internal/gardener/shoot/extender/oidc_test.go
  internal/gardener/shoot/extender/provider.go
  internal/gardener/shoot/extender/provider_test.go
  internal/gardener/shoot/hyperscaler/const.go
  internal/gardener/shoot/hyperscaler/openstack/config.go
  internal/gardener/shoot/hyperscaler/openstack/config_test.go
  internal/gardener/shoot/hyperscaler/sapconvergedcloud/config.go
Labels: size/XL, lgtm, cla: yes

#269 networking filter and cloud profile extenders
  go.mod
  internal/controller/runtime_controller.go
  internal/gardener/shoot/converter.go
  internal/gardener/shoot/converter_test.go
  internal/gardener/shoot/extender/exposure_classname_extender.go
  internal/gardener/shoot/extender/exposure_classname_extender_test.go
  internal/gardener/shoot/extender/kubernetes_version_test.go
  internal/gardener/shoot/extender/network_filter.go
  internal/gardener/shoot/extender/network_filter_test.go
Labels: lgtm, size/L, cla: yes

#247 Implementing Runtime Reconciler with a state machine
  .github/workflows/golangci-lint.yaml
  api/v1/runtime_types.go
  cmd/main.go
  config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
  config/manager/kustomization.yaml
  config/samples/infrastructuremanager_v1_runtime.yaml
  go.mod
  go.sum
  internal/controller/kubeconfig/find_last_sync_time.go
  internal/controller/kubeconfig/find_last_sync_time_test.go
  internal/controller/kubeconfig/gardener_cluster_controller.go
  internal/controller/kubeconfig/gardener_cluster_controller_test.go
  internal/controller/kubeconfig/mocks/KubeconfigProvider.go
  internal/controller/kubeconfig/next_requeue.go
  internal/controller/kubeconfig/next_requeue_test.go
  internal/controller/kubeconfig/suite_test.go
  internal/controller/runtime/fsm/runtime_fsm.go
  internal/controller/runtime/fsm/runtime_fsm_common.go
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_delete_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_emit_event.go
  internal/controller/runtime/fsm/runtime_fsm_finalizer_matcher_test.go
  internal/controller/runtime/fsm/runtime_fsm_fn_name_matcher_test.go
  internal/controller/runtime/fsm/runtime_fsm_initialise.go
  internal/controller/runtime/fsm/runtime_fsm_initialise_test.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot_test.go
  internal/controller/runtime/fsm/runtime_fsm_prepare_cluster.go
  internal/controller/runtime/fsm/runtime_fsm_prepare_cluster_test.go
  internal/controller/runtime/fsm/runtime_fsm_process_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_take_snapshot.go
  internal/controller/runtime/fsm/runtime_fsm_update_status.go
  internal/controller/runtime/fsm/runtime_state.go
  internal/controller/runtime/fsm/state_fn_instance_status_matcher_test.go
  internal/controller/runtime/fsm/suite_test.go
  internal/controller/runtime/fsm/testing/shoot.go
  internal/controller/runtime/fsm/utilz_for_test.go
  internal/controller/runtime/runtime_controller.go
  internal/controller/runtime/runtime_controller_test.go
  internal/controller/runtime/suite_test.go
  internal/controller/runtime_controller.go
  internal/gardener/client.go
  internal/gardener/mocks/ShootClient.go
Labels: size/XXL, area/ci, lgtm, cla: yes
