Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2024-03, with the labels that each got.

#146 [IM] Rename the GitHub Actions
  .github/workflows/daily-markdown-link-check.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/pr-markdown-link-check.yaml
  .github/workflows/run-tests.yaml
  .github/workflows/run-vuln-check.yaml
Labels: area/ci, size/S, lgtm, cla: yes

#119 infrastructure manager metrics (2/n)
  .github/workflows/run-vuln-check.yaml
  Dockerfile
  Makefile
  cmd/main.go
  internal/controller/gardener_cluster_controller.go
  internal/controller/gardener_cluster_controller_test.go
  internal/controller/metrics/metrics.go
  internal/controller/suite_test.go
Labels: area/ci, lgtm, size/L, cla: yes

#147 Batch of dependabot fixes
  go.mod
  go.sum
Labels: lgtm, size/L, cla: yes

#148 Unordered lists are appropriate for items that have no sequential order
  docs/contributor/testing-strategy.md
Labels: area/documentation, lgtm, size/M, cla: yes
