Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2024-02, with the labels that each got.

#143 renames LICENCE file to LICENSE
  LICENSE
Labels: size/XS, lgtm, cla: yes

#133 Add testing strategy for Infrastructure Manager
  docs/contributor/testing-strategy.md
Labels: area/documentation, lgtm, size/L, cla: yes

#144 upgrades golangci-lint to v4 in IM
  .github/workflows/golangci-lint.yaml
  internal/controller/find_last_sync_time_test.go
  internal/controller/gardener_cluster_controller_test.go
  internal/controller/next_requeue_test.go
  internal/controller/suite_test.go
Labels: area/ci, lgtm, size/M, cla: yes
