Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2025-03, with the labels that each got.

#708 switch from CxSAST to CxONE
  sec-scanners-config.yaml
Labels: size/S, lgtm

#686 Add converter debug tool
  api/v1/runtime_types.go
  hack/patch-converter-runner/README.md
  hack/patch-converter-runner/cmd/main.go
  hack/patch-converter-runner/go.mod
  hack/patch-converter-runner/go.sum
  hack/patch-converter-runner/script/run.sh
  pkg/gardener/shoot/converter.go
  pkg/gardener/shoot/extender/kubernetes.go
  pkg/gardener/shoot/extender/kubernetes_test.go
  pkg/gardener/shoot/extender/provider/provider.go
  pkg/gardener/shoot/extender/provider/provider_aws_test.go
  pkg/gardener/shoot/extender/provider/provider_azure_test.go
  pkg/gardener/shoot/extender/provider/provider_gcp_test.go
  pkg/gardener/shoot/extender/provider/provider_openstack_test.go
  pkg/gardener/shoot/extender/provider/provider_test.go
Labels: size/XL, lgtm, cla: yes

#713 Registry caching ADR
  docs/adr/002-registry-cache.md
  docs/adr/README.md
  docs/adr/assets/caching-in-kim.drawio.svg
Labels: area/documentation, lgtm, size/L

#694 Reduce logs
  internal/controller/kubeconfig/gardener_cluster_controller.go
  internal/controller/runtime/fsm/runtime_fsm.go
  internal/controller/runtime/fsm/runtime_fsm_apply_clusterrolebindings.go
  internal/controller/runtime/fsm/runtime_fsm_configure_oidc.go
  internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig.go
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_delete_kubeconfig.go
  internal/controller/runtime/fsm/runtime_fsm_delete_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_initialise.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_select_shoot_processing.go
  internal/controller/runtime/fsm/runtime_fsm_take_snapshot.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go
  internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
  internal/controller/runtime/runtime_controller.go
  internal/log_level/log_level.go
Labels: size/L, cla: yes

#715 Adding support for Gardener's DNS solution in shoot-dns-service, and allow DNS converter config data to be empty
  go.mod
  go.sum
  hack/patch-converter-runner/go.mod
  hack/patch-converter-runner/go.sum
  hack/performance/go.mod
  hack/performance/go.sum
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/go.sum
  pkg/config/config.go
  pkg/gardener/shoot/converter.go
  pkg/gardener/shoot/extender/extensions/dns.go
  pkg/gardener/shoot/extender/extensions/dns_test.go
  pkg/gardener/shoot/extender/extensions/extender.go
Labels: size/L
