Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2025-01, with the labels that each got.

#591 Implement backup and restore for Cluster Role Bindings and OIDC
  hack/runtime-migrator/cmd/backup/backup.go
  hack/runtime-migrator/cmd/backup/main.go
  hack/runtime-migrator/cmd/restore/main.go
  hack/runtime-migrator/cmd/restore/restore.go
  hack/runtime-migrator/internal/backup/backup.go
  hack/runtime-migrator/internal/backup/output.go
  hack/runtime-migrator/internal/initialisation/client.go
  hack/runtime-migrator/internal/initialisation/params.go
  hack/runtime-migrator/internal/restore/backupreader.go
  hack/runtime-migrator/internal/restore/restorer.go
  hack/runtime-migrator/internal/restore/results.go
  hack/runtime-migrator/internal/shoot/util.go
Labels: size/XL, lgtm, cla: yes

#594 Add handling of LastOperationStateError shoot operation state while waiting for reconciliation to complete
  internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go
  internal/controller/runtime/suite_test.go
Labels: size/S, lgtm, cla: yes

#595 adds more retryable gardener error codes
  pkg/gardener/gardener_error_handler.go
  pkg/gardener/gardener_error_handler_test.go
Labels: lgtm, size/L, cla: yes

#592 Backup restore 4
  hack/runtime-migrator/cmd/backup/backup.go
  hack/runtime-migrator/cmd/backup/main.go
  hack/runtime-migrator/cmd/migration/migration.go
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/internal/backup/backup.go
  hack/runtime-migrator/internal/backup/results.go
  hack/runtime-migrator/internal/initialisation/params.go
  hack/runtime-migrator/internal/migration/migrator.go
  hack/runtime-migrator/internal/restore/results.go
  hack/runtime-migrator/internal/shoot/workers.go
Labels: lgtm, size/L, cla: yes

#597 Update x/net lib to 0.34
  go.mod
  go.sum
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/go.sum
Labels: lgtm, size/M, cla: yes

#598 Update go-jose lib to fix MEND findings
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/go.sum
Labels: size/XS, lgtm, cla: yes

#596 Add readme files for Backup and Restore
  hack/runtime-migrator/README-rb.md
  hack/runtime-migrator/README-rm.md
  hack/runtime-migrator/README-rr.md
  hack/runtime-migrator/cmd/backup-and-switch/backup.go
  hack/runtime-migrator/cmd/backup-and-switch/main.go
  hack/runtime-migrator/cmd/migration/main.go
  hack/runtime-migrator/cmd/restore/restore.go
  hack/runtime-migrator/internal/backup/output.go
  hack/runtime-migrator/internal/initialisation/params.go
  hack/runtime-migrator/internal/shoot/labels.go
Labels: lgtm, size/L, cla: yes

#576 Implement CRB cleanup
  hack/runtime-migrator/cmd/crb-cleanup/Makefile
  hack/runtime-migrator/cmd/crb-cleanup/README.md
  hack/runtime-migrator/cmd/crb-cleanup/cleaner.go
  hack/runtime-migrator/cmd/crb-cleanup/config.go
  hack/runtime-migrator/cmd/crb-cleanup/crb_cleanup_suite_test.go
  hack/runtime-migrator/cmd/crb-cleanup/fetcher.go
  hack/runtime-migrator/cmd/crb-cleanup/main.go
  hack/runtime-migrator/cmd/crb-cleanup/main_test.go
  hack/runtime-migrator/cmd/crb-cleanup/utils.go
  hack/runtime-migrator/cmd/crb-cleanup/utils_test.go
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/go.sum
Labels: size/XL, lgtm, cla: yes
