Repository kyma-project/kyma-infrastructure-manager, pull requests merged in 2025-02, with the labels that each got.

#612 support forcing and suspending reconciliation
  config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
  config/rbac/role.yaml
  docs/README.md
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot_test.go
  internal/controller/runtime/fsm/runtime_fsm_select_shoot_processing.go
  internal/controller/runtime/fsm/runtime_fsm_select_shoot_processing_test.go
  internal/controller/runtime/fsm/testing/fake_k8s_client_config.go
  internal/controller/runtime/fsm/utilz_for_test.go
  internal/controller/runtime/suite_test.go
  pkg/reconciler/annotations_utils.go
  pkg/reconciler/annotations_utils_test.go
  pkg/reconciler/verify_reconciler_test.go
Labels: area/documentation, size/XL, lgtm, cla: yes

#654 Update golang version to 1.23.6
  .github/workflows/golangci-lint.yaml
  .github/workflows/run-tests.yaml
  .github/workflows/run-vuln-check.yaml
  Dockerfile
  go.mod
  hack/performance/go.mod
  hack/performance/go.sum
  hack/runtime-migrator/go.mod
  hack/shoot-comparator/Dockerfile
  hack/shoot-comparator/go.mod
  hack/shoot-comparator/go.sum
Labels: area/ci, lgtm, size/M, cla: yes

#656 Extend set of worker network zones during shoot update
  pkg/gardener/shoot/extender/provider.go
Labels: area/ci, size/S, lgtm, cla: yes

#657 Adjust unit tests for functionality of extending workers network zones config
  pkg/gardener/shoot/extender/provider.go
  pkg/gardener/shoot/extender/provider_test.go
Labels: lgtm, size/M, cla: yes

#623 Add checks for seed availability in the create state
  api/v1/runtime_types.go
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/seed.go
  internal/controller/runtime/runtime_controller_test.go
  internal/controller/runtime/suite_test.go
  internal/controller/runtime/test_client_obj_tracker.go
  internal/controller/runtime/test_client_obj_tracker_test.go
Labels: lgtm, size/L, cla: yes

#650 KIM - Fix of the problem with removing exiting shoots using client.Update function to change shoot workers
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot_test.go
  internal/controller/runtime/fsm/testing/fake_k8s_client_config.go
  internal/controller/runtime/fsm/utilz_for_test.go
Labels: lgtm, size/L, cla: yes

#646 Cleanup dry run mode, and shoot spec writing
  api/v1/runtime_types.go
  api/v1/runtime_types_test.go
  cmd/main.go
  internal/controller/runtime/fsm/runtime_fsm.go
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_create_shoot_dry_run.go
  internal/controller/runtime/fsm/runtime_fsm_initialise.go
  internal/controller/runtime/fsm/runtime_fsm_initialise_test.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_persist_shoot_test.go
  internal/controller/runtime/fsm/runtime_fsm_take_snapshot.go
  internal/controller/runtime/fsm/utilz_for_test.go
  internal/controller/runtime/runtime_controller_test.go
Labels: size/XL, lgtm, cla: yes

#664 Fix of provider extender for legacy azure-lite shoots where networking zones are not specified in the infrastructureConfig
  pkg/gardener/shoot/extender/provider.go
  pkg/gardener/shoot/extender/provider_test.go
Labels: lgtm, size/M, cla: yes

#660 retry forbidden patch request
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
Labels: lgtm, size/M, cla: yes

#649 Cleanup remaining code related to dry-run functionality
  .github/workflows/build_shoot_compare.yml
  cmd/main.go
  docs/README.md
  internal/controller/runtime/fsm/utilz_for_test.go
Labels: area/documentation, area/ci, lgtm, size/M, cla: yes

#666 fail a test in order to test tide replacement
  pkg/gardener/shoot/extender/annotations_test.go
Labels: size/XS, cla: yes

#667 Revert "fail a test in order to test tide replacement"
  pkg/gardener/shoot/extender/annotations_test.go
Labels: size/XS, cla: yes

#668 add gh workflow that should assure that all checks are passed before the merge
  .github/workflows/all-checks-passed.yml
Labels: area/ci, size/S, cla: yes

#651 Cleanup hack folder: remove backup, restore, and shoot-comparator tools
  hack/runtime-migrator/README-rb.md
  hack/runtime-migrator/README-rr.md
  hack/runtime-migrator/README.md
  hack/runtime-migrator/cmd/backup-and-switch/backup.go
  hack/runtime-migrator/cmd/backup-and-switch/main.go
  hack/runtime-migrator/cmd/migration/migration.go
  hack/runtime-migrator/cmd/restore/main.go
  hack/runtime-migrator/cmd/restore/restore.go
  hack/runtime-migrator/go.mod
  hack/runtime-migrator/go.sum
  hack/runtime-migrator/internal/backup/backup.go
  hack/runtime-migrator/internal/backup/output.go
  hack/runtime-migrator/internal/backup/results.go
  hack/runtime-migrator/internal/migration/output.go
  hack/runtime-migrator/internal/migration/verifier.go
  hack/runtime-migrator/internal/restore/backupreader.go
  hack/runtime-migrator/internal/restore/output.go
  hack/runtime-migrator/internal/restore/results.go
  hack/shoot-comparator/Dockerfile
  hack/shoot-comparator/README.md
  hack/shoot-comparator/cmd/comparator/comparator.go
  hack/shoot-comparator/cmd/comparator/directories.go
  hack/shoot-comparator/cmd/comparator/files.go
  hack/shoot-comparator/cmd/main.go
  hack/shoot-comparator/go.mod
  hack/shoot-comparator/go.sum
  hack/shoot-comparator/internal/directories/comparator.go
  hack/shoot-comparator/internal/directories/comparator_test.go
  hack/shoot-comparator/internal/directories/report.go
  hack/shoot-comparator/internal/files/comparator.go
  hack/shoot-comparator/pkg/errors/errors.go
  hack/shoot-comparator/pkg/runtime/raw_extension_matcher.go
  hack/shoot-comparator/pkg/runtime/raw_extension_matcher_test.go
  hack/shoot-comparator/pkg/runtime/testdata/infra_cfg_azure_11.yaml
  hack/shoot-comparator/pkg/runtime/testdata/infra_cfg_azure_12.yaml
  hack/shoot-comparator/pkg/runtime/testdata/infra_cfg_azure_21.yaml
  hack/shoot-comparator/pkg/runtime/testdata/infra_cfg_openstack_11.yaml
  hack/shoot-comparator/pkg/shoot/matcher.go
  hack/shoot-comparator/pkg/shoot/matcher_test.go
  hack/shoot-comparator/pkg/shoot/provider_cfg_matcher.go
  hack/shoot-comparator/pkg/shoot/provider_matcher.go
  hack/shoot-comparator/pkg/shoot/suite_test.go
  hack/shoot-comparator/pkg/utilz/utilz.go
  hack/shoot-comparator/scripts/README.md
  hack/shoot-comparator/scripts/cleanup-comparison-resources.sh
  hack/shoot-comparator/scripts/fetch_shoots_for_provisioner_and_kim.sh
  hack/shoot-comparator/scripts/manifests/fetch-kim-and-provisioner-files.yaml
  hack/shoot-comparator/scripts/manifests/fetch-results-pod.yaml
  hack/shoot-comparator/scripts/manifests/job.yaml
  hack/shoot-comparator/scripts/manifests/mount-kim-volume-with-write-access.yaml
  hack/shoot-comparator/scripts/manifests/mount-prov-volume-with-write-access.yaml
  hack/shoot-comparator/scripts/manifests/snapshot-for-comparison.yaml
  hack/shoot-comparator/scripts/run_comparison.sh
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
Labels: size/XXL, area/documentation, area/ci, lgtm, cla: yes

#672 Remove crb cleanup
  hack/runtime-migrator/cmd/crb-cleanup/Makefile
  hack/runtime-migrator/cmd/crb-cleanup/README.md
  hack/runtime-migrator/cmd/crb-cleanup/cleaner.go
  hack/runtime-migrator/cmd/crb-cleanup/config.go
  hack/runtime-migrator/cmd/crb-cleanup/crb_cleanup_suite_test.go
  hack/runtime-migrator/cmd/crb-cleanup/fetcher.go
  hack/runtime-migrator/cmd/crb-cleanup/main.go
  hack/runtime-migrator/cmd/crb-cleanup/main_test.go
  hack/runtime-migrator/cmd/crb-cleanup/utils.go
  hack/runtime-migrator/cmd/crb-cleanup/utils_test.go
  hack/runtime-migrator/go.mod
Labels: size/XL, lgtm, cla: yes

#682 First approach to fixing worker synchronisation problem
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot_test.go
  internal/controller/runtime/suite_test.go
Labels: lgtm, size/M, cla: yes

#685 Fix problem with Gardener validation failure during update of a worker pool with one node
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  pkg/gardener/shoot/converter.go
  pkg/gardener/shoot/extender/provider.go
  pkg/gardener/shoot/extender/provider_aws_test.go
  pkg/gardener/shoot/extender/provider_azure_test.go
  pkg/gardener/shoot/extender/provider_gcp_test.go
  pkg/gardener/shoot/extender/provider_openstack_test.go
  pkg/gardener/shoot/extender/provider_test.go
Labels: size/XXL, lgtm, cla: yes

#688 Handling Gardener error ERR_CONFIGURATION_PROBLEM as retryable
  pkg/gardener/gardener_error_handler.go
  pkg/gardener/gardener_error_handler_test.go
Labels: size/S, lgtm, cla: yes

#671 Implement configuration of the cluster MaintenanceTimeWindow in KIM
  api/v1/runtime_types.go
  config/default/kustomization.yaml
  config/default/manager_maintenance_window_patch.yaml
  internal/controller/runtime/fsm/maintenanceWindow.go
  internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
  internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
  internal/controller/runtime/runtime_controller_test.go
  internal/controller/runtime/suite_test.go
  internal/controller/runtime/testdata/maintenanceWindow.yaml
  pkg/config/config.go
  pkg/gardener/shoot/converter.go
  pkg/gardener/shoot/converter_test.go
  pkg/gardener/shoot/extender/annotations_test.go
  pkg/gardener/shoot/extender/cert_config_test.go
  pkg/gardener/shoot/extender/cloud_profile_test.go
  pkg/gardener/shoot/extender/dns_test.go
  pkg/gardener/shoot/extender/exposure_classname_extender_test.go
  pkg/gardener/shoot/extender/kubernetes_test.go
  pkg/gardener/shoot/extender/labels_test.go
  pkg/gardener/shoot/extender/maintenance/get_maintenance_window.go
  pkg/gardener/shoot/extender/maintenance/maintenance.go
  pkg/gardener/shoot/extender/maintenance/maintenance_test.go
  pkg/gardener/shoot/extender/network_filter_test.go
  pkg/gardener/shoot/extender/oidc_test.go
  pkg/gardener/shoot/extender/provider_aws_test.go
  pkg/gardener/shoot/extender/provider_azure_test.go
  pkg/gardener/shoot/extender/provider_gcp_test.go
  pkg/gardener/shoot/extender/provider_openstack_test.go
  pkg/gardener/shoot/extender/provider_test.go
  pkg/gardener/shoot/extender/seed_selector_test.go
  pkg/gardener/shoot/extender/testutils/fixtures.go
  pkg/gardener/shoot/extender/tolerations_test.go
Labels: size/L, cla: yes
